use SatisVT

--DATE SORGULARI
--Örnek datapart sorgularý

select *from TBL_HAREKET where DATEPART(day,TARIH) between 1 and 3
--1 ve 3 ekimde sehri ankara olan sorguyu yazýnýz
select *from TBL_HAREKET where DATEPART(day,TARIH) between 1 and 3 and
MUSTERI=(select MUSTERIID from TBL_MUSTERI WHERE MUSTERISEHIR='ANKARA')

--Datename Fonksiyonu

select DATENAME(month,getdate()) as monthgetdate ,datename(month,'2019.01.15') as monthdate
select datename(day,getdate())
select datename(weekday,getdate())
select datename(weekday,'2022.01.03')

--DateDiff Fonksiyonu ->bugunun tarihinden kac yýl gecmis
select DATEDIFF(YEAR,'2010.10.25',GETDATE())
SELECT DATEDIFF(MONTH,'2010.06.14','2015.08.06')
SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBL_HAREKET WHERE HAREKETID=1

--DateAdd Fonkisyonu
select DATEADD(year,3,'2009-10.25')
select DATEADD(day,45,getdate())
select DATEADD(month,350,getdate())

--ALT SORGU ÖRNEKLERÝ
select *from TBL_MUSTERI

--SORU: Ürünler içerisinde her bir üründen kaç adet satýlmýs?
select urunad,count(*) 'urun adet' from TBL_HAREKET INNER JOIN
TBL_URUNLER on TBL_URUNLER.URUNID=TBL_HAREKET.URUN group by urunad order by count(*) asc

SELECT *FROM TBL_HAREKET WHERE URUN=(SELECT URUNID FROM TBL_URUNLER WHERE KATEGORI=1)--HATA VERÝR
SELECT *FROM TBL_HAREKET WHERE URUN IN (SELECT URUNID FROM TBL_URUNLER WHERE KATEGORI=1)

--Urunler ýcersinde  kategori =bilgisayar ele yazýp getiren sorgu

--ÝÇ ÝÇE SORGU
SELECT *FROM TBL_HAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBL_MUSTERI WHERE MUSTERISEHIR='ANKARA')

SELECT *FROM TBL_HAREKET WHERE URUN IN (SELECT URUNID FROM TBL_URUNLER WHERE
KATEGORI=(SELECT KATEGORIID FROM TBL_KATEGORI WHERE KATEGORIADI='BEYAZ EÞYA'))
--SORU:adanalý veya ankaralý musterilere satýlan urunlerin toplam fiyatý bulan sorgu
select sum(tutar),MUSTERISEHIR from TBL_HAREKET INNER JOIN TBL_MUSTERI ON 
TBL_MUSTERI.MUSTERIID=TBL_HAREKET.MUSTERI where MUSTERI IN(SELECT MUSTERIID FROM TBL_MUSTERI 
WHERE MUSTERISEHIR='ANKARA' or  MUSTERISEHIR='ADANA') group by MUSTERISEHIR

select *from TBL_HAREKET where URUN=1
update TBL_URUNLER set URUNSTOK=URUNSTOK-(select sum(ADET) from TBL_HAREKET where URUN=1)
where URUNID=1

--KASA TABLOSU
CREATE TABLE TBL_KASA(

TOPLAM DECIMAL(18,2)
)
--DROP TABLE TBLKASA
INSERT INTO TBL_KASA VALUES(0)
SELECT *FROM TBL_KASA
UPDATE TBL_KASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBL_HAREKET)

--Tetikleyiciler(Trigger Oluþturma)
CREATE TABLE TBL_SAYAC(
ISLEM INT
)

INSERT INTO TBL_SAYAC VALUES(0)
UPDATE TBL_SAYAC SET ISLEM=(SELECT COUNT(*)FROM TBL_HAREKET)

CREATE TRIGGER ISLEMARIS
ON TBL_HAREKET
AFTER INSERT
AS
UPDATE TBL_SAYAC SET ISLEM=ISLEM+1

--OTOMATÝK OLARAK BÝR ÝSLEM OLDUGUNDA GUNCELLENÝR.

CREATE TABLE TBLTOPLAMKATEGORI
(
ADET TINYINT 
)
--drop table TBLTOPLAMKATEGORI
UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBL_KATEGORI)

CREATE TRIGGER KATEGORIARTIS
ON TBL_KATEGORI
AFTER INSERT
AS
UPDATE TBLTOPLAMKATEGORI SET ADET=ADET+1

--DROP TRIGGER KATEGORIAZALIS

CREATE TRIGGER KATEGORIAZALIS
ON TBL_KATEGORI
AFTER DELETE
AS
UPDATE TBLTOPLAMKATEGORI SET ADET-=1

--VIEW
--View oluþturma ve kullanýmý

CREATE VIEW TEST1
AS
SELECT*FROM TBL_KATEGORI

SELECT *FROM TEST1

ALTER VIEW TEST1
AS
SELECT *FROM TBL_KATEGORI WHERE KATEGORIID<4

DROP VIEW TEST1

--View sihirbazý kullanýmý

--SELECT dbo.TBL_URUNLER.URUNID, dbo.TBL_URUNLER.URUNAD, dbo.TBL_URUNLER.URUNMARKA, dbo.TBL_KATEGORI.KATEGORIADI
--FROM     dbo.TBL_KATEGORI INNER JOIN
--                  dbo.TBL_URUNLER ON dbo.TBL_KATEGORI.KATEGORIID = dbo.TBL_URUNLER.KATEGORI
--WHERE  (TBL_URUNLER.URUNAD LIKE '%a')
SELECT *FROM TEST2

--View'ýn dezavantajý dýþardan parametre almamasý


--View hareket tablosu
SELECT dbo.TBL_URUNLER.URUNAD, dbo.TBL_MUSTERI.MUSTERIAD, dbo.TBL_MUSTERI.MUSTERISOYAD, dbo.TBL_PERSONEL.PERSONELADSOYAD, dbo.TBL_HAREKET.ADET, dbo.TBL_HAREKET.TUTAR, dbo.TBL_HAREKET.TARIH
FROM     dbo.TBL_HAREKET INNER JOIN
                  dbo.TBL_URUNLER ON dbo.TBL_HAREKET.URUN = dbo.TBL_URUNLER.URUNID INNER JOIN
                  dbo.TBL_PERSONEL ON dbo.TBL_HAREKET.PERSONEL = dbo.TBL_PERSONEL.PERSONELID INNER JOIN
                  dbo.TBL_MUSTERI ON dbo.TBL_HAREKET.MUSTERI = dbo.TBL_MUSTERI.MUSTERIID

SELECT *FROM TEST3

SELECT dbo.TBL_URUNLER.URUNAD, dbo.TBL_MUSTERI.MUSTERIAD, dbo.TBL_MUSTERI.MUSTERISOYAD, dbo.TBL_PERSONEL.PERSONELADSOYAD, dbo.TBL_HAREKET.ADET, dbo.TBL_HAREKET.TUTAR, dbo.TBL_HAREKET.TARIH
FROM     dbo.TBL_HAREKET INNER JOIN
                  dbo.TBL_URUNLER ON dbo.TBL_HAREKET.URUN = dbo.TBL_URUNLER.URUNID INNER JOIN
                  dbo.TBL_PERSONEL ON dbo.TBL_HAREKET.PERSONEL = dbo.TBL_PERSONEL.PERSONELID INNER JOIN
                  dbo.TBL_MUSTERI ON dbo.TBL_HAREKET.MUSTERI = dbo.TBL_MUSTERI.MUSTERIID
WHERE  (dbo.TBL_HAREKET.ADET > 1)