--GRUPLANDIRMALAR VE OPERATORLER
SELECT COUNT(*)FROM TBL_OGRENCILER
SELECT COUNT(*) AS 'Toplam Kiþi' FROM TBL_OGRENCILER
SELECT COUNT(*) AS'Toplam Kayýt' FROM TBL_OGRENCILER WHERE OGRSEHIR='AdANA'

SELECT SUM(SINAV1) FROM TBL_NOTLAR
SELECT SUM(SINAV1)AS'SINAV1 TOPLAM', SUM(SINAV2)AS 'SINAV2 TOPLAM', SUM(SINAV3)AS'SINAV3 TOPLAM' FROM TBL_NOTLAR

SELECT AVG(SINAV1)AS'SINAV1 ORT', AVG(SINAV2)AS 'SINAV2 ORT', AVG(SINAV3)AS'SINAV3 ORT' FROM TBL_NOTLAR

SELECT MAX(SINAV1) FROM TBL_NOTLAR
SELECT MAX(SINAV1)AS'SINAV1 MAX', MAX(SINAV2)AS 'SINAV2 MAX', MAX(SINAV3)AS'SINAV3 MAX' FROM TBL_NOTLAR

SELECT MIN(SINAV1)AS'SINAV1 MIN', MIN(SINAV2)AS 'SINAV2 MIN',MIN(SINAV3)AS'SINAV3 MIN' FROM TBL_NOTLAR