select *from TBL_OGRENCILER

select *from TBL_OGRENCILER where OGRSEHIR='Ýzmir' or OGRKULUP='Satranç'

SELECT (SINAV1+SINAV2+SINAV3)/3 FROM TBL_NOTLAR 

SELECT *FROM TBL_OGRENCILER
Insert Into TBL_OGRENCILER(OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('Baran','Yucedað','Elazýð')

Insert Into TBL_NOTLAR (OGRENCI,DERS,SINAV1,SINAV3) VALUES(6,2,88,67)

--DELETE
DELETE FROM TBLDERSLER
DELETE FROM TBLDERSLER WHERE DERSID=6

--TRUNCATE
TRUNCATE TABLE TBLDERSLER

UPDATE
UPDATE TBL_OGRENCILER SET OGRCINSIYET='Erkek'--Tum tablodaki ogrcinsiyet degerini erkek yaptý
UPDATE TBL_OGRENCILER SET OGRCINSIYET='Kýz' WHERE OGRID=4 OR OGRID=2 OR OGRID=5--Þart eklememiz gerekiyor.
UPDATE TBL_OGRENCILER SET OGRKULUP='Kitaplýk' WHERE OGRAD='Baran'

INSERT INTO TBL_NOTLAR (OGRENCI,DERS,SINAV1,SINAV2) VALUES(5,2,78,66)
UPDATE TBL_NOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 
UPDATE TBL_NOTLAR SET DURUM=1 WHERE ORTALAMA>=50
