use DbOgrenciNot

create table TBL_KULUPLER(
KULUPID TINYINT IDENTITY(1,1),
KULUPAD VARCHAR(20)

);

INSERT INTO TBL_KULUPLER VALUES('Biliþim')
INSERT INTO TBL_KULUPLER VALUES('Kitaplýk')
INSERT INTO TBL_KULUPLER VALUES('Satranç')
INSERT INTO TBL_KULUPLER VALUES('Gezi')
INSERT INTO TBL_KULUPLER VALUES('Temizlik')

UPDATE TBL_OGRENCILER SET OGRKULUP=1 WHERE OGRKULUP='Biliþim'
UPDATE TBL_OGRENCILER SET OGRKULUP=2 WHERE OGRKULUP='Kitaplýk'
UPDATE TBL_OGRENCILER SET OGRKULUP=3 WHERE OGRKULUP='Satranç'
UPDATE TBL_OGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'

--Tablodaki sutunun tipini degistirme
Alter Table TBL_OGRENCILER alter column OGRKULUP tinyint
--Tablodaki sütunu primary key yapma
Alter Table TBL_OGRENCILER add PRIMARY KEY(OGRID )
Alter Table TBL_KULUPLER add PRIMARY KEY(KULUPID )

INSERT INTO TBL_OGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES('Berna',4,'Ankara')